/*
	Strategy
	Authors: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType								)
VALUES 	('LEADER_CVS_ANTIOCHUS_III_TECHS'		),
		('LEADER_CVS_ANTIOCHUS_III_CIVICS'		),
		('LEADER_CVS_ANTIOCHUS_III_DISTRICTS'	),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS'	),
		('LEADER_CVS_ANTIOCHUS_III_PROJECTS'	),
		('LEADER_CVS_ANTIOCHUS_III_DIPLOMACY'	),
		('LEADER_CVS_ANTIOCHUS_III_TACTICS'		),
		('LEADER_CVS_ANTIOCHUS_III_EXPANSION'	),
		('LEADER_CVS_ANTIOCHUS_III_PSUEDOS'		);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,								AgendaType,					System				)
VALUES  ('LEADER_CVS_ANTIOCHUS_III_TECHS',		'AGENDA_CVS_ANTIOCHUS_III',	'Technologies'		),
		('LEADER_CVS_ANTIOCHUS_III_CIVICS',		'AGENDA_CVS_ANTIOCHUS_III',	'Civics'			),
		('LEADER_CVS_ANTIOCHUS_III_DISTRICTS',	'AGENDA_CVS_ANTIOCHUS_III',	'Districts'			),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'AGENDA_CVS_ANTIOCHUS_III',	'Buildings'			),
		('LEADER_CVS_ANTIOCHUS_III_PROJECTS',	'AGENDA_CVS_ANTIOCHUS_III',	'Projects'			),
		('LEADER_CVS_ANTIOCHUS_III_TACTICS',	'AGENDA_CVS_ANTIOCHUS_III',	'Tactics'			),
		('LEADER_CVS_ANTIOCHUS_III_DIPLOMACY',	'AGENDA_CVS_ANTIOCHUS_III',	'DiplomaticActions'	),
		('LEADER_CVS_ANTIOCHUS_III_EXPANSION',	'AGENDA_CVS_ANTIOCHUS_III',	'PlotEvaluations'	),
		('LEADER_CVS_ANTIOCHUS_III_PSUEDOS',	'AGENDA_CVS_ANTIOCHUS_III',	'PsuedoYields'		);

-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,								Item,									Favored	)
VALUES  -- TECHS
		('LEADER_CVS_ANTIOCHUS_III_TECHS',		'TECH_ARCHERY',							1		),
		('LEADER_CVS_ANTIOCHUS_III_TECHS',		'TECH_BRONZE_WORKING',					1		),
		('LEADER_CVS_ANTIOCHUS_III_TECHS',		'TECH_HORSEBACK_RIDING',				1		),
		('LEADER_CVS_ANTIOCHUS_III_TECHS',		'TECH_IRON_WORKING',					1		),
		('LEADER_CVS_ANTIOCHUS_III_TECHS',		'TECH_CURRENCY',						1		),
		('LEADER_CVS_ANTIOCHUS_III_TECHS',		'TECH_MILITARY_ENGINEERING',			1		),
		('LEADER_CVS_ANTIOCHUS_III_TECHS',		'TECH_CASTLES',							1		),
		('LEADER_CVS_ANTIOCHUS_III_TECHS',		'TECH_SIEGE_TACTICS',					1		),
		-- CIVICS
		('LEADER_CVS_ANTIOCHUS_III_CIVICS',		'CIVIC_FOREIGN_TRADE',					1		),
		('LEADER_CVS_ANTIOCHUS_III_CIVICS',		'CIVIC_MILITARY_TRADITION',				1		),
		('LEADER_CVS_ANTIOCHUS_III_CIVICS',		'CIVIC_MILITARY_TRAINING',				1		),
		-- DISTRICTS
		('LEADER_CVS_ANTIOCHUS_III_DISTRICTS',	'DISTRICT_CVS_SELEUCID_UI',				1		),
		('LEADER_CVS_ANTIOCHUS_III_DISTRICTS',	'DISTRICT_ENCAMPMENT',					1		),
		-- BUILDINGS
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_WALLS',						1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_BARRACKS',					1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_STABLE',						1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_ARMORY',						1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_MILITARY_ACADEMY',			1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_MARKET',						1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_BANK',						1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_STOCK_EXCHANGE',				1		),
		-- WONDERS
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_ALHAMBRA',					1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_PETRA',						1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_GREAT_ZIMBABWE',				1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_HANGING_GARDENS',				1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_PYRAMIDS',					1		),
		('LEADER_CVS_ANTIOCHUS_III_BUILDINGS',	'BUILDING_TERRACOTTA_ARMY',				1		);
		-- PROJECTS
		-- TACTICS
		-- DIPLOMACY

INSERT INTO AiFavoredItems
		(ListType,								Item,						Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CVS_ANTIOCHUS_III_EXPANSION',	'Resource Class',			1,			5,		'RESOURCECLASS_STRATEGIC'	),
		-- PSUEDOS
		('LEADER_CVS_ANTIOCHUS_III_PSUEDOS',	'PSEUDOYIELD_UNIT_TRADE',	1,			5,		NULL						),
		('LEADER_CVS_ANTIOCHUS_III_PSUEDOS',	'PSEUDOYIELD_GPP_GENERAL',	1,			50,		NULL						),
		('LEADER_CVS_ANTIOCHUS_III_PSUEDOS',	'PSEUDOYIELD_UNIT_COMBAT',	1,			30,		NULL						),
		('LEADER_CVS_ANTIOCHUS_III_PSUEDOS',	'PSEUDOYIELD_INFLUENCE',	1,			25,		NULL						);
