/*
	Mod Support RwF
	Authors: ChimpanG
*/

-----------------------------------------------
-- JFD'S RULE WITH FAITH
-----------------------------------------------

CREATE TABLE IF NOT EXISTS 
	Civilization_Titles (
	CivilizationType		TEXT	DEFAULT NULL,
	GovernmentType			TEXT	DEFAULT NULL,
	LeaderTitle				TEXT	DEFAULT NULL,
	PolicyType				TEXT	DEFAULT NULL
	);

CREATE TABLE IF NOT EXISTS 
	Leader_Titles (
	LeaderType	TEXT 			 		DEFAULT NULL,
	GovernmentType			TEXT		DEFAULT NULL,
	LeaderTitle				TEXT		DEFAULT NULL,
	PolicyType  			TEXT 		DEFAULT NULL,
	UseFeminine				BOOLEAN		DEFAULT 0,
	TitleIsFullName			BOOLEAN		DEFAULT 0
	);
	
INSERT INTO Civilization_Titles
		(CivilizationType, 				GovernmentType, 							PolicyType,				LeaderTitle																		)
VALUES	('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_CHIEFDOM',						NULL,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SELEUCID'							), -- Chiefdom
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_HORDE',						NULL,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SELEUCID'							), -- Horde
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_POLIS',						NULL,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SELEUCID'							), -- Polis
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_AUTOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SELEUCID'						), -- Autocracy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_OLIGARCHY',						NULL,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SELEUCID'						), -- Oligarchy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_CLASSICAL_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SELEUCID'				), -- Classical Democracy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_MONARCHY',						NULL,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SELEUCID'					), -- Feudal Monarchy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_MERCHANT_REPUBLIC',				NULL,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SELEUCID'				), -- Merchant Republic
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_THEOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SELEUCID'				), -- Theocracy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SELEUCID'							), -- Absolute Monarchy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SELEUCID'							), -- Constitutional Monarchy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SELEUCID'						), -- Noble Republic
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_DEMOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SELEUCID'				), -- Liberal Democracy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_COMMUNISM',						NULL,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SELEUCID'					), -- People's Republic
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_FASCISM',						NULL,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SELEUCID'			), -- Military Guardianship
		('CIVILIZATION_CVS_SELEUCID',	NULL,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SELEUCID'							), -- Empire
		
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_CHIEFDOM',						NULL,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SELEUCID_FEMININE'				), -- Chiefdom
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_HORDE',						NULL,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SELEUCID_FEMININE'					), -- Horde
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_POLIS',						NULL,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SELEUCID_FEMININE'					), -- Polis
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_AUTOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SELEUCID_FEMININE'				), -- Autocracy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_OLIGARCHY',						NULL,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SELEUCID_FEMININE'				), -- Oligarchy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_CLASSICAL_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SELEUCID_FEMININE'		), -- Classical Democracy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_MONARCHY',						NULL,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SELEUCID_FEMININE'			), -- Feudal Monarchy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_MERCHANT_REPUBLIC',				NULL,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SELEUCID_FEMININE'		), -- Merchant Republic
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_THEOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SELEUCID_FEMININE'	), -- Theocracy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SELEUCID_FEMININE'				), -- Absolute Monarchy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	NULL,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SELEUCID_FEMININE'				), -- Constitutional Monarchy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			NULL,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SELEUCID_FEMININE'				), -- Noble Republic
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_DEMOCRACY',						NULL,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SELEUCID_FEMININE'		), -- Liberal Democracy
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_COMMUNISM',						NULL,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SELEUCID_FEMININE'		), -- People's Republic
		('CIVILIZATION_CVS_SELEUCID',	'GOVERNMENT_FASCISM',						NULL,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SELEUCID_FEMININE'	), -- Military Guardianship
		('CIVILIZATION_CVS_SELEUCID',	NULL,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SELEUCID_FEMININE'				); -- Empire
