/*
	Mod Support RwF Localisation
	Authors: ChimpanG
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT OR REPLACE INTO BaseGameText
		(Tag,																				Text						)
VALUES	("LOC_CIVILIZATION_CVS_SELEUCID_DESCRIPTION_JFD_CIVILIZATION",						"Seleucid Civilization"		),

		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SELEUCID",							"Chief"						),
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SELEUCID_FEMININE",					"Chief"						),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SELEUCID",								"Polemarch"					),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SELEUCID_FEMININE",						"Polemarch"					),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SELEUCID",								"Politarch"					),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SELEUCID_FEMININE",						"Politarch"					),

		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SELEUCID",							"Archon"					),
		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SELEUCID_FEMININE",					"Archontissa"				),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SELEUCID",							"Ephor"						),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SELEUCID_FEMININE",					"Ephorissa"					),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SELEUCID",				"Speaker"					),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SELEUCID_FEMININE",		"Speaker"					),

		("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SELEUCID",					"Anax"						),
		("LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SELEUCID_FEMININE",			"Anassa"					),
		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SELEUCID",					"Magistros"					),
		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SELEUCID_FEMININE",			"Magistrissa"				),
		("LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SELEUCID",				"Sultan"					),
		("LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SELEUCID_FEMININE",		"Sultan"					),

		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SELEUCID",							"Basilius"					),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SELEUCID_FEMININE",					"Basileia"					),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_CVS_SELEUCID",						"Grand Logothete"			),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_CVS_SELEUCID_FEMININE",			"Grand Logothete"			),
		
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SELEUCID",					"Speaker"					),
		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SELEUCID_FEMININE",			"Speaker"					),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SELEUCID",					"Chairman"					),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SELEUCID_FEMININE",			"Chairman"					),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SELEUCID",				"Tyrant"					),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SELEUCID_FEMININE",		"Tyrantess"					),
		
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_SELEUCID",								"Basileus"					),
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_CVS_SELEUCID_FEMININE",					"Basileia"					);
